"""Admin settings and AI analysis helpers."""

from __future__ import annotations

import hashlib
import json
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from app.core.config import get_settings
from app.schemas import (
    AiConfig,
    AiConfigResponse,
    AiConfigUpdate,
    EvalAnalysisItem,
    EvalAnalysisRequest,
    EvalAnalysisResponse,
)

DEFAULT_ADMIN_PASSWORD = "cbir-admin"
DEFAULT_AI_CONFIG = AiConfig()


def admin_config_path() -> Path:
    """Return the private backend config file path."""

    path = get_settings().data_root_path / "admin_config.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def verify_admin_password(password: str) -> bool:
    """Check the admin password for the local demo system."""

    expected = os.getenv("CBIR_ADMIN_PASSWORD", DEFAULT_ADMIN_PASSWORD)
    return _digest(password) == _digest(expected)


def make_admin_token(password: str) -> str:
    """Create a deterministic local admin token."""

    day = int(time.time() // 86400)
    secret = os.getenv("CBIR_ADMIN_SECRET", "cbir-local-admin")
    return _digest(f"{secret}:{password}:{day}")


def verify_admin_token(token: str) -> bool:
    """Validate a token generated by the current or previous day."""

    expected_password = os.getenv("CBIR_ADMIN_PASSWORD", DEFAULT_ADMIN_PASSWORD)
    secret = os.getenv("CBIR_ADMIN_SECRET", "cbir-local-admin")
    day = int(time.time() // 86400)
    valid = {
        _digest(f"{secret}:{expected_password}:{day}"),
        _digest(f"{secret}:{expected_password}:{day - 1}"),
    }
    return token in valid


def read_ai_config() -> AiConfig:
    """Read AI config from the private config file."""

    path = admin_config_path()
    if not path.exists():
        return DEFAULT_AI_CONFIG.model_copy()
    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)
    return AiConfig(**data)


def write_ai_config(update: AiConfigUpdate) -> AiConfigResponse:
    """Persist AI config and return a safe response."""

    current = read_ai_config()
    api_key = update.api_key.strip() or current.api_key
    config = AiConfig(
        enabled=update.enabled,
        provider=update.provider.strip() or "deepseek",
        base_url=(update.base_url.strip() or "https://api.deepseek.com").rstrip("/"),
        model=update.model.strip() or "deepseek-v4-flash",
        vision_model=update.vision_model.strip(),
        api_key=api_key,
    )
    with admin_config_path().open("w", encoding="utf-8") as file:
        json.dump(config.model_dump(), file, ensure_ascii=False, indent=2)
    return safe_ai_config(config)


def safe_ai_config(config: AiConfig | None = None) -> AiConfigResponse:
    """Return AI config without exposing the secret key."""

    config = config or read_ai_config()
    return AiConfigResponse(
        enabled=config.enabled,
        provider=config.provider,
        base_url=config.base_url,
        model=config.model,
        vision_model=config.vision_model,
        has_api_key=bool(config.api_key),
        api_key_hint=_mask_key(config.api_key),
    )


def analyze_evaluation(request: EvalAnalysisRequest) -> EvalAnalysisResponse:
    """Use a configured OpenAI-compatible model to analyze evaluation metrics."""

    config = read_ai_config()
    if not config.enabled:
        raise ValueError("AI 分析未启用，请先到管理员页面开启")
    if not config.api_key:
        raise ValueError("AI API Key 未配置，请先到管理员页面保存 Key")
    if config.provider.lower() != "deepseek":
        raise ValueError("当前仅支持 DeepSeek 兼容接口")

    payload = {
        "model": config.model,
        "messages": [
            {
                "role": "system",
                "content": (
                    "你是一个内容检索系统实验分析助手。请用中文分析 CBIR 评估结果，"
                    "重点解释 mAP、P@K、PR 曲线差异、特征优缺点和后续改进建议。"
                    "不要编造不存在的数据，只基于用户提供的指标。"
                ),
            },
            {"role": "user", "content": _analysis_prompt(request)},
        ],
        "temperature": 0.2,
        "stream": False,
    }
    data = _post_json(
        f"{config.base_url}/chat/completions",
        payload,
        {"Authorization": f"Bearer {config.api_key}"},
    )
    content = (
        data.get("choices", [{}])[0]
        .get("message", {})
        .get("content", "")
        .strip()
    )
    if not content:
        raise ValueError("AI 服务没有返回有效分析内容")
    return EvalAnalysisResponse(provider=config.provider, model=config.model, content=content)


def _analysis_prompt(request: EvalAnalysisRequest) -> str:
    rows = "\n".join(_format_eval_item(item) for item in request.items)
    best_map = max(request.items, key=lambda item: item.map, default=None)
    best_pk = max(request.items, key=lambda item: item.p_at_k, default=None)
    best_text = ""
    if best_map and best_pk:
        best_text = (
            f"\n当前 mAP 最高：{best_map.feature_label}={best_map.map:.4f}；"
            f"P@{best_pk.k} 最高：{best_pk.feature_label}={best_pk.p_at_k:.4f}。"
        )
    return (
        f"数据集：{request.dataset}\n"
        f"相似度度量：{request.metric}\n"
        f"评估样本数：{request.sample}\n"
        f"评估结果：\n{rows}"
        f"{best_text}\n"
        "请输出：1.总体结论；2.各特征对比；3.PR 曲线如何解读；4.系统改进建议。"
    )


def _format_eval_item(item: EvalAnalysisItem) -> str:
    curve_preview = item.pr_curve[:5]
    return (
        f"- {item.feature_label}({item.feature}): "
        f"mAP={item.map:.4f}, P@{item.k}={item.p_at_k:.4f}, "
        f"query={item.query_count}, elapsed={item.elapsed_ms:.1f}ms, "
        f"PR前5点={curve_preview}"
    )


def _post_json(url: str, payload: dict[str, Any], headers: dict[str, str]) -> dict[str, Any]:
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={
            "Content-Type": "application/json",
            **headers,
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            raw = response.read().decode("utf-8")
            return json.loads(raw)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="ignore")
        raise ValueError(f"AI 服务请求失败：HTTP {exc.code} {detail}") from exc
    except urllib.error.URLError as exc:
        raise ValueError(f"AI 服务连接失败：{exc.reason}") from exc


def _mask_key(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "****"
    return f"{value[:4]}****{value[-4:]}"


def _digest(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()
